export const COMMENTARIES = [
  {
    "id": 1,
    "item_id": 1000,
    "text": "Commodo nisi duis culpa nulla mollit ut qui. Culpa velit nulla voluptate pariatur officia aute irure minim eu. Officia enim fugiat tempor velit commodo.",
    "date": "15.06.2017",
    "name": "Николай",
  },
  {
    "id": 2,
    "item_id": 1001,
    "text": "Adipisicing do reprehenderit eu laboris non voluptate dolor cupidatat ullamco. Nisi veniam non ut mollit sit et nisi ea eiusmod enim quis. Lorem eu eiusmod aute sint consequat labore consectetur esse incididunt.",
    "date": "27.05.2017",
    "name": "Николай",
  },
  {
    "id": 3,
    "item_id": 1002,
    "text": "Amet est occaecat enim deserunt. Officia deserunt enim in veniam ullamco anim minim eiusmod deserunt excepteur magna. Eu duis pariatur commodo nostrud aliquip veniam fugiat minim ipsum culpa sunt.",
    "date": "20.01.2020",
    "name": "Любовь",
  },
  {
    "id": 4,
    "item_id": 1003,
    "text": "Culpa dolor et ex nulla aliquip adipisicing fugiat nisi nisi minim anim irure qui dolor. Ex minim ullamco qui dolore officia labore proident id. Labore nisi consequat aliquip nisi est reprehenderit.",
    "date": "27.01.2016",
    "name": "Елизавета",
  },
  {
    "id": 5,
    "item_id": 1004,
    "text": "Laborum deserunt qui reprehenderit laborum aute ipsum ut consectetur est incididunt est. Enim nulla esse aliquip fugiat do elit aliquip magna commodo ex duis ullamco aliquip. Aute Lorem laboris tempor reprehenderit dolor sunt enim velit excepteur.",
    "date": "20.02.2014",
    "name": "Алексей",
  },
  {
    "id": 6,
    "item_id": 1005,
    "text": "Incididunt mollit officia dolore officia ullamco amet nostrud ad adipisicing laboris magna fugiat eu. Sit elit enim nulla sunt anim consequat occaecat tempor ea in. Ex proident Lorem aute cillum mollit velit.",
    "date": "03.12.2018",
    "name": "Дмитрий",
  },
  {
    "id": 7,
    "item_id": 1006,
    "text": "Veniam tempor culpa laborum aliquip Lorem proident Lorem aute exercitation dolor et commodo. Magna proident cupidatat esse Lorem et officia laborum proident cillum ut voluptate laborum pariatur. Cupidatat consequat dolor incididunt sit cillum proident irure eu non occaecat ea commodo magna.",
    "date": "14.11.2017",
    "name": "Ксения",
  },
  {
    "id": 8,
    "item_id": 1007,
    "text": "Dolor veniam aliqua ut labore id ut. Qui culpa minim veniam et mollit laborum non consequat anim reprehenderit ullamco aliqua. Veniam aliquip sit magna velit est aliqua consectetur id occaecat commodo dolore.",
    "date": "24.11.2014",
    "name": "Александра",
  },
  {
    "id": 9,
    "item_id": 1008,
    "text": "Exercitation deserunt laborum quis nisi Lorem Lorem ex cupidatat esse laborum. Fugiat commodo ea sit minim nisi minim culpa anim aliqua culpa. Fugiat dolore adipisicing magna eu reprehenderit reprehenderit amet nostrud ex ipsum.",
    "date": "24.03.2016",
    "name": "Роза",
  },
  {
    "id": 10,
    "item_id": 1009,
    "text": "Est sunt commodo enim veniam in commodo dolor laboris in duis occaecat dolore anim ut. Deserunt aliqua ad ex ad elit mollit non ullamco. Culpa cupidatat sit ipsum pariatur cillum et cupidatat consectetur pariatur esse velit.",
    "date": "21.05.2018",
    "name": "Анастасия",
  },
  {
    "id": 11,
    "item_id": 1010,
    "text": "Velit ea incididunt pariatur enim labore laborum ipsum commodo non est magna. Non cupidatat in nulla veniam esse nostrud Lorem ad aute dolore. Veniam adipisicing mollit aliquip nostrud dolor ipsum adipisicing sint.",
    "date": "11.09.2020",
    "name": "Ахмед",
  },
  {
    "id": 12,
    "item_id": 1011,
    "text": "Quis ut commodo tempor do nostrud sunt sunt ea consectetur culpa. Cillum consequat nisi laborum voluptate dolor. Mollit adipisicing consectetur quis ex magna velit laboris pariatur ipsum sint sit officia esse.",
    "date": "12.11.2018",
    "name": "Любовь",
  },
  {
    "id": 13,
    "item_id": 1012,
    "text": "Consequat quis sint qui esse. Et exercitation eiusmod culpa veniam esse. Lorem sunt anim proident non dolore in occaecat occaecat aute.",
    "date": "26.02.2020",
    "name": "Дмитрий",
  },
  {
    "id": 14,
    "item_id": 1013,
    "text": "Et commodo id minim qui ullamco aliquip anim ut. Veniam esse cillum officia consectetur eiusmod qui id ipsum amet labore amet. Sint ad aute ut qui velit officia labore amet dolor.",
    "date": "27.03.2014",
    "name": "Роза",
  },
  {
    "id": 15,
    "item_id": 1014,
    "text": "Sint do dolore dolor do excepteur minim eu do deserunt aliqua in aute consequat cillum. Consectetur tempor veniam aliquip deserunt ullamco aliqua consequat ex labore ut enim sint culpa voluptate. Sint ex eu nostrud sunt cillum laboris veniam esse pariatur enim fugiat occaecat veniam sint.",
    "date": "30.09.2017",
    "name": "Ахмед",
  },
  {
    "id": 16,
    "item_id": 1015,
    "text": "Cupidatat veniam laborum cupidatat id ex cillum dolore consectetur veniam amet pariatur qui ad occaecat. Laborum dolore consectetur commodo Lorem excepteur esse labore tempor quis Lorem pariatur duis. Reprehenderit nulla ut nostrud ex aliqua sint ad.",
    "date": "19.04.2020",
    "name": "Кирилл",
  },
  {
    "id": 17,
    "item_id": 1016,
    "text": "Lorem quis qui amet ut id ad do laborum quis cupidatat anim irure magna. Duis tempor qui ea cillum aliquip. Laboris in voluptate nostrud proident cillum.",
    "date": "21.04.2014",
    "name": "Андрей",
  },
  {
    "id": 18,
    "item_id": 1017,
    "text": "Lorem occaecat ad ad reprehenderit velit ut cillum nostrud nostrud. Eiusmod et sit magna enim sint reprehenderit nulla consequat do irure sunt ipsum pariatur dolor. Laborum id deserunt id nisi eiusmod cupidatat.",
    "date": "07.12.2018",
    "name": "Ахмед",
  },
  {
    "id": 19,
    "item_id": 1018,
    "text": "Aute ea qui consequat esse et dolor excepteur enim officia culpa ut laborum eiusmod. Et nisi nisi sit sit excepteur ad amet adipisicing elit sit eiusmod reprehenderit id duis. Quis voluptate adipisicing velit dolore aliqua reprehenderit occaecat magna.",
    "date": "15.07.2017",
    "name": "Екатерина",
  },
  {
    "id": 20,
    "item_id": 1019,
    "text": "Ullamco labore nostrud est ullamco aute consequat do mollit. Nostrud adipisicing laborum ullamco ipsum voluptate occaecat irure voluptate anim deserunt anim pariatur minim. Ex id deserunt in dolor.",
    "date": "26.01.2018",
    "name": "Роза",
  },
  {
    "id": 21,
    "item_id": 1020,
    "text": "Qui eu laborum eu deserunt. In Lorem officia duis sunt voluptate cillum nostrud. Commodo cupidatat nulla magna dolore proident.",
    "date": "11.01.2016",
    "name": "Александра",
  },
  {
    "id": 22,
    "item_id": 1021,
    "text": "Magna excepteur fugiat excepteur ea. Cillum mollit sunt elit id. Pariatur do occaecat id deserunt dolore amet et exercitation dolor.",
    "date": "28.09.2014",
    "name": "Алексей",
  },
  {
    "id": 23,
    "item_id": 1022,
    "text": "Ipsum Lorem nostrud duis consequat id dolore tempor adipisicing labore tempor et fugiat. Sint fugiat sint officia mollit ea consectetur aliquip aliquip. Consectetur sint duis esse consectetur.",
    "date": "02.01.2020",
    "name": "Николай",
  },
  {
    "id": 24,
    "item_id": 1023,
    "text": "Fugiat irure in tempor dolore laboris ullamco deserunt non labore nisi culpa exercitation. Reprehenderit enim irure eiusmod dolore aute laborum exercitation ut tempor reprehenderit non magna consequat ex. Aliquip aute pariatur velit voluptate fugiat magna voluptate reprehenderit.",
    "date": "08.11.2017",
    "name": "Артём",
  },
  {
    "id": 25,
    "item_id": 1024,
    "text": "Nostrud ad cupidatat exercitation adipisicing et. Minim dolor ut est in in ut ea minim ea amet. Incididunt anim dolore velit do ipsum ipsum laboris.",
    "date": "22.08.2015",
    "name": "Роза",
  },
  {
    "id": 26,
    "item_id": 1025,
    "text": "Cupidatat ex excepteur ullamco duis sint quis Lorem enim. Eiusmod veniam culpa quis do incididunt id ea. Velit et qui tempor aliqua nisi pariatur pariatur veniam mollit nulla occaecat.",
    "date": "18.07.2020",
    "name": "Артём",
  },
  {
    "id": 27,
    "item_id": 1026,
    "text": "Aute excepteur occaecat Lorem aute reprehenderit. Exercitation ex mollit consectetur irure anim sint. Dolor tempor pariatur sint sit cillum esse irure qui occaecat nostrud ad tempor irure veniam.",
    "date": "27.08.2018",
    "name": "Кирилл",
  },
  {
    "id": 28,
    "item_id": 1027,
    "text": "Mollit sit consectetur id elit magna consectetur magna veniam excepteur ex. Excepteur ea sunt commodo ipsum. Ullamco fugiat deserunt aute est qui sint irure dolor esse.",
    "date": "09.12.2015",
    "name": "Ахмед",
  },
  {
    "id": 29,
    "item_id": 1028,
    "text": "Proident ut est duis voluptate ut. Proident nulla culpa aliquip veniam eu officia anim consequat proident nulla do ullamco do. Incididunt reprehenderit ut velit dolore laborum culpa nisi.",
    "date": "05.05.2014",
    "name": "Дмитрий",
  },
  {
    "id": 30,
    "item_id": 1029,
    "text": "Voluptate dolor elit minim ex non aliquip dolore magna consequat enim cupidatat id amet. Magna anim ut proident amet laboris. Sint tempor veniam dolor eiusmod excepteur sit elit qui do.",
    "date": "21.11.2016",
    "name": "Кирилл",
  },
  {
    "id": 31,
    "item_id": 1030,
    "text": "Et dolor amet cillum veniam nostrud mollit qui. Duis minim proident magna minim nulla magna et deserunt ex. Eu minim dolore esse irure aliqua adipisicing aute sit.",
    "date": "27.10.2014",
    "name": "Артём",
  },
  {
    "id": 32,
    "item_id": 1031,
    "text": "Veniam esse proident sunt cillum et aliqua commodo sit adipisicing culpa. Minim veniam sit eu fugiat ex id irure velit irure reprehenderit fugiat proident. Reprehenderit reprehenderit consequat do duis nulla eu est irure esse et proident consequat officia.",
    "date": "14.08.2015",
    "name": "Ксения",
  },
  {
    "id": 33,
    "item_id": 1032,
    "text": "Laborum sunt duis dolor laboris aute incididunt mollit Lorem. Mollit nulla eiusmod exercitation reprehenderit minim eu ipsum ad. Irure eiusmod velit sunt minim cupidatat nisi quis consectetur sit.",
    "date": "24.08.2018",
    "name": "Любовь",
  },
  {
    "id": 34,
    "item_id": 1033,
    "text": "Excepteur pariatur esse enim exercitation aliqua. Nisi cillum sint ipsum culpa velit anim mollit nulla sint ut amet pariatur nisi enim. Amet eiusmod incididunt aute deserunt aliquip culpa occaecat.",
    "date": "07.06.2019",
    "name": "Ксения",
  },
  {
    "id": 35,
    "item_id": 1034,
    "text": "Culpa anim occaecat laborum elit laboris veniam enim laboris. Nulla non incididunt cupidatat eiusmod ex nisi mollit cillum aliqua aliquip nulla aliquip irure. Occaecat culpa et sunt commodo labore dolor deserunt enim amet velit exercitation est.",
    "date": "09.10.2017",
    "name": "Дмитрий",
  },
  {
    "id": 36,
    "item_id": 1035,
    "text": "Non adipisicing dolore reprehenderit do. Nisi aute laboris dolore in occaecat sunt Lorem qui. Aute veniam et in non ea nostrud quis incididunt dolore magna ex.",
    "date": "02.03.2016",
    "name": "Кирилл",
  },
  {
    "id": 37,
    "item_id": 1036,
    "text": "Aute cillum fugiat enim eu exercitation velit tempor. Deserunt cupidatat id adipisicing sit aliqua nisi voluptate. Aliqua est incididunt culpa proident irure cupidatat sit aliqua.",
    "date": "19.11.2015",
    "name": "Андрей",
  },
  {
    "id": 38,
    "item_id": 1037,
    "text": "Quis cupidatat tempor irure irure non eu consectetur nulla laborum est. Adipisicing est nulla veniam cillum cillum occaecat sint fugiat. Magna nostrud aliqua exercitation dolor ut excepteur enim ullamco.",
    "date": "10.06.2016",
    "name": "Дмитрий",
  },
  {
    "id": 39,
    "item_id": 1038,
    "text": "Duis nulla commodo pariatur cupidatat do duis ut voluptate ullamco dolor magna. Et Lorem velit consectetur labore cupidatat ex voluptate amet voluptate laborum ea. Ullamco ea pariatur ea consequat eiusmod consectetur tempor elit id non irure culpa esse.",
    "date": "07.11.2020",
    "name": "Николай",
  },
  {
    "id": 40,
    "item_id": 1039,
    "text": "Excepteur mollit laboris dolor commodo occaecat sunt. Laboris ad irure Lorem ipsum proident sunt do excepteur veniam labore irure id exercitation ad. Consequat culpa tempor nostrud commodo laboris cillum reprehenderit consectetur aliquip est aliqua dolore dolor ut.",
    "date": "23.01.2014",
    "name": "Кирилл",
  },
  {
    "id": 41,
    "item_id": 1040,
    "text": "Ad est do id pariatur cillum reprehenderit mollit sit minim tempor. Tempor eu elit nulla cillum non fugiat minim consectetur non non nisi veniam quis. Est adipisicing Lorem ad proident consequat consectetur.",
    "date": "10.11.2017",
    "name": "Артём",
  },
  {
    "id": 42,
    "item_id": 1041,
    "text": "Dolore reprehenderit mollit duis ullamco adipisicing ut non. Sit nulla non aute ea labore consequat. Labore fugiat fugiat aute Lorem nostrud dolor Lorem aliqua consequat dolor magna.",
    "date": "03.10.2014",
    "name": "Любовь",
  },
  {
    "id": 43,
    "item_id": 1042,
    "text": "Mollit nulla qui sint aute qui eu amet est. Esse cillum exercitation eu mollit ad do ad ipsum elit eiusmod do qui. Do exercitation adipisicing eu est excepteur consequat anim culpa et ad labore proident.",
    "date": "30.03.2014",
    "name": "Алексей",
  },
  {
    "id": 44,
    "item_id": 1043,
    "text": "Ad ut ut dolore minim consequat excepteur officia ullamco mollit. Aliquip culpa quis veniam sint non commodo nisi voluptate anim consectetur velit ad. Ea aliquip qui et quis aliquip do veniam ullamco irure enim aliqua excepteur.",
    "date": "04.07.2017",
    "name": "Дмитрий",
  },
  {
    "id": 45,
    "item_id": 1044,
    "text": "Dolor magna id fugiat ad et ipsum sit. Pariatur elit nostrud quis irure do. Voluptate do sit consequat dolore laboris.",
    "date": "30.03.2019",
    "name": "Николай",
  },
  {
    "id": 46,
    "item_id": 1045,
    "text": "Aliquip voluptate ipsum voluptate est pariatur sunt consequat. Excepteur cupidatat quis culpa id aute pariatur irure elit magna sit est. Consequat et pariatur veniam esse laborum eiusmod nulla fugiat nisi ex occaecat ullamco duis eu.",
    "date": "26.03.2017",
    "name": "Анастасия",
  },
  {
    "id": 47,
    "item_id": 1046,
    "text": "Magna elit amet adipisicing voluptate in elit occaecat exercitation deserunt anim do. Mollit dolore eu excepteur eu esse eiusmod adipisicing et ea incididunt. Cillum dolor proident ullamco ipsum irure ad.",
    "date": "04.02.2019",
    "name": "Алексей",
  },
  {
    "id": 48,
    "item_id": 1047,
    "text": "Reprehenderit pariatur pariatur deserunt dolore Lorem ex excepteur mollit commodo laboris incididunt consectetur commodo ad. Irure laborum in ad minim dolor dolor proident cillum. Dolore sunt exercitation laboris deserunt ipsum quis ad aliqua pariatur officia.",
    "date": "28.04.2016",
    "name": "Дмитрий",
  },
  {
    "id": 49,
    "item_id": 1048,
    "text": "Velit excepteur fugiat officia sunt sunt est amet mollit nostrud fugiat eu ex culpa commodo. Duis consequat excepteur reprehenderit aute sunt anim occaecat eu et. Tempor irure veniam laboris eu veniam qui amet.",
    "date": "15.03.2015",
    "name": "Алексей",
  },
  {
    "id": 50,
    "item_id": 1049,
    "text": "Velit dolore nisi ad dolore anim deserunt adipisicing quis aliquip esse pariatur. Dolore consectetur dolor incididunt exercitation anim magna labore do. Duis esse aliqua cillum eu consequat.",
    "date": "02.05.2018",
    "name": "Ксения",
  },
  {
    "id": 1,
    "item_id": 1000,
    "text": "Ipsum qui et laborum esse. Nulla enim ad aliqua officia elit commodo exercitation in id. Ex mollit reprehenderit incididunt tempor deserunt nostrud qui.",
    "date": "23.06.2018",
    "name": "Роза",
  },
  {
    "id": 2,
    "item_id": 1001,
    "text": "Magna veniam laboris sit dolore culpa laboris excepteur ut. Ut eiusmod officia in sunt proident irure pariatur aliquip laboris. Qui ea cupidatat anim sit dolore proident sint esse incididunt exercitation quis cupidatat fugiat reprehenderit.",
    "date": "14.12.2017",
    "name": "Дмитрий",
  },
  {
    "id": 3,
    "item_id": 1002,
    "text": "Nisi enim veniam occaecat ea. Laborum labore consequat aliqua ea eiusmod adipisicing sit. Pariatur et aute veniam ipsum aliqua tempor irure fugiat irure proident.",
    "date": "18.11.2019",
    "name": "Роза",
  },
  {
    "id": 4,
    "item_id": 1003,
    "text": "Nulla do enim do ut nisi velit. Eiusmod mollit esse officia reprehenderit et velit qui nulla ut consectetur. Cillum Lorem ipsum Lorem voluptate amet magna nulla labore id Lorem voluptate eiusmod commodo dolor.",
    "date": "10.04.2015",
    "name": "Ахмед",
  },
  {
    "id": 5,
    "item_id": 1004,
    "text": "Consequat do proident proident minim voluptate laborum mollit tempor mollit reprehenderit esse voluptate laboris dolore. Est anim veniam cillum magna non ut id. Cillum laboris labore culpa esse voluptate minim sit laboris amet anim sit laboris.",
    "date": "21.09.2017",
    "name": "Екатерина",
  },
  {
    "id": 6,
    "item_id": 1005,
    "text": "Nisi adipisicing minim elit dolore adipisicing ad ullamco reprehenderit fugiat adipisicing culpa voluptate proident. Enim non eiusmod reprehenderit Lorem incididunt. Occaecat exercitation magna nostrud commodo do dolor adipisicing ullamco cillum reprehenderit sint consectetur.",
    "date": "24.05.2020",
    "name": "Екатерина",
  },
  {
    "id": 7,
    "item_id": 1006,
    "text": "Sit duis ut veniam elit nulla eu veniam occaecat laboris. Sint reprehenderit incididunt voluptate qui laborum. Velit duis occaecat pariatur nulla nostrud aute.",
    "date": "31.03.2016",
    "name": "Роза",
  },
  {
    "id": 8,
    "item_id": 1007,
    "text": "Officia minim cupidatat minim aute reprehenderit irure velit sit nulla in ut nostrud ex. Mollit reprehenderit laboris mollit incididunt ullamco eiusmod incididunt. Esse enim ea nulla ad elit nisi fugiat est velit fugiat incididunt non reprehenderit.",
    "date": "10.05.2017",
    "name": "Любовь",
  },
  {
    "id": 9,
    "item_id": 1008,
    "text": "Sint laboris incididunt tempor enim reprehenderit culpa. Laborum exercitation eu anim incididunt eu consequat ex magna officia. Esse consequat anim dolor dolor ullamco deserunt.",
    "date": "18.03.2018",
    "name": "Александра",
  },
  {
    "id": 10,
    "item_id": 1009,
    "text": "Quis in ex duis sint. Sint ad nostrud consequat quis irure. Est tempor in officia sint laboris voluptate proident deserunt.",
    "date": "03.05.2018",
    "name": "Ахмед",
  },
  {
    "id": 11,
    "item_id": 1010,
    "text": "Sit laboris fugiat id in esse ullamco. Pariatur eiusmod consequat dolore nulla ad qui irure consequat. Eiusmod veniam duis elit dolor quis eu.",
    "date": "12.09.2016",
    "name": "Василий",
  },
  {
    "id": 12,
    "item_id": 1011,
    "text": "Cillum occaecat non enim eiusmod sit nostrud ad est adipisicing commodo laboris excepteur ex est. Occaecat aliquip cillum aliqua nulla anim aliqua. Reprehenderit non aliqua cillum amet deserunt aute eu nulla culpa amet mollit sit.",
    "date": "28.06.2015",
    "name": "Дмитрий",
  },
  {
    "id": 13,
    "item_id": 1012,
    "text": "Dolor aliquip labore sint consectetur sint irure pariatur nulla sint Lorem id id. Est tempor magna magna magna eiusmod nostrud Lorem laborum amet et amet do. Minim sint reprehenderit ad aute elit culpa amet eiusmod incididunt ea deserunt sint.",
    "date": "14.03.2017",
    "name": "Наталья",
  },
  {
    "id": 14,
    "item_id": 1013,
    "text": "Consequat commodo nostrud nisi laborum ut. Quis do eu officia excepteur non ex exercitation dolor id est duis mollit quis et. Tempor exercitation culpa cillum laboris nostrud occaecat enim.",
    "date": "23.01.2014",
    "name": "Любовь",
  },
  {
    "id": 15,
    "item_id": 1014,
    "text": "Nostrud sunt et anim enim id laboris nulla ut enim proident nostrud consectetur. Dolore fugiat minim nisi in occaecat duis amet dolore velit magna mollit esse qui. Tempor anim nostrud duis proident.",
    "date": "03.10.2014",
    "name": "Елизавета",
  },
  {
    "id": 16,
    "item_id": 1015,
    "text": "Ut officia exercitation adipisicing deserunt esse reprehenderit non veniam Lorem. Cupidatat esse exercitation dolore mollit aliqua laboris enim et qui id non duis commodo nulla. Id duis anim irure est ex.",
    "date": "28.07.2019",
    "name": "Анастасия",
  },
  {
    "id": 17,
    "item_id": 1016,
    "text": "Sunt duis nulla aute aliquip non qui consectetur nulla cillum magna laboris. Eiusmod adipisicing sint incididunt elit proident voluptate nostrud. Ad duis exercitation in laborum laboris.",
    "date": "13.02.2018",
    "name": "Дмитрий",
  },
  {
    "id": 18,
    "item_id": 1017,
    "text": "Ea duis tempor id sunt quis amet sunt cillum laboris nisi sint fugiat. Irure aliqua pariatur dolor eu culpa velit est do. Duis voluptate esse consequat do quis dolor aliqua consectetur.",
    "date": "20.08.2016",
    "name": "Анастасия",
  },
  {
    "id": 19,
    "item_id": 1018,
    "text": "Esse occaecat eu nisi minim sint laboris commodo minim aliquip cupidatat eiusmod do cillum adipisicing. Reprehenderit ullamco id commodo labore voluptate sunt commodo proident ullamco. Ad in cillum aliqua voluptate labore culpa magna aliquip laboris.",
    "date": "08.09.2019",
    "name": "Алексей",
  },
  {
    "id": 20,
    "item_id": 1019,
    "text": "Enim nulla occaecat cupidatat quis consequat eu nulla officia ut irure ut quis dolore. Sunt ut dolor eu ipsum. Cupidatat nisi in ipsum dolore voluptate et voluptate veniam ut reprehenderit commodo aute deserunt.",
    "date": "05.01.2020",
    "name": "Александра",
  },
  {
    "id": 21,
    "item_id": 1020,
    "text": "Magna exercitation officia incididunt in consequat mollit commodo minim est reprehenderit proident irure fugiat. Enim ipsum deserunt Lorem dolor eu ad fugiat ipsum voluptate. Aliqua excepteur aliquip veniam nostrud officia sint ipsum est nisi pariatur laboris quis veniam deserunt.",
    "date": "01.06.2018",
    "name": "Любовь",
  },
  {
    "id": 22,
    "item_id": 1021,
    "text": "Occaecat enim Lorem consectetur occaecat in pariatur velit laboris occaecat incididunt. Adipisicing ullamco ex laboris reprehenderit labore sit excepteur commodo. Consequat duis aliquip deserunt nostrud occaecat dolore.",
    "date": "07.01.2016",
    "name": "Николай",
  },
  {
    "id": 23,
    "item_id": 1022,
    "text": "Laborum deserunt eiusmod deserunt elit tempor aute do minim magna labore est ipsum ad aliquip. Aliqua sunt eu Lorem sunt proident ad minim sit aute elit mollit nostrud amet. Laboris culpa voluptate voluptate magna mollit nostrud ipsum nostrud aliqua sint magna cupidatat non.",
    "date": "28.10.2019",
    "name": "Александра",
  },
  {
    "id": 24,
    "item_id": 1023,
    "text": "Esse excepteur excepteur sit sunt reprehenderit ullamco irure nulla. Eu et culpa labore incididunt. Reprehenderit qui est deserunt sint.",
    "date": "13.11.2014",
    "name": "Василий",
  },
  {
    "id": 25,
    "item_id": 1024,
    "text": "Ipsum in ipsum velit ut ut deserunt laboris enim incididunt laboris ipsum. Enim irure ea nulla quis in in laboris est minim non irure. Anim est dolore ea nisi magna esse fugiat sit ad amet.",
    "date": "20.01.2015",
    "name": "Алексей",
  },
  {
    "id": 26,
    "item_id": 1025,
    "text": "Enim fugiat dolore ea officia. Voluptate cupidatat nostrud magna magna do dolore nulla enim enim est nisi nulla. Est culpa tempor nulla eiusmod.",
    "date": "18.06.2019",
    "name": "Александра",
  },
  {
    "id": 27,
    "item_id": 1026,
    "text": "Ex in occaecat veniam est commodo fugiat ex consectetur. Deserunt esse mollit laboris labore ut ipsum reprehenderit laborum reprehenderit sint commodo. Veniam sint dolore occaecat non.",
    "date": "17.08.2017",
    "name": "Николай",
  },
  {
    "id": 28,
    "item_id": 1027,
    "text": "Magna proident commodo eiusmod id do sit sit non aliquip dolor dolore. Enim in consectetur reprehenderit duis anim consectetur. Ex quis duis duis pariatur consequat veniam id voluptate ea Lorem.",
    "date": "21.01.2014",
    "name": "Алексей",
  },
  {
    "id": 29,
    "item_id": 1028,
    "text": "Laboris in et ad enim sint eiusmod adipisicing commodo ullamco excepteur proident. Cillum do incididunt esse magna enim sunt culpa ea culpa. Culpa deserunt minim ad sint laboris nulla anim est id.",
    "date": "28.02.2016",
    "name": "Роза",
  },
  {
    "id": 30,
    "item_id": 1029,
    "text": "Ipsum non esse irure ipsum duis consectetur nisi. Consectetur id officia qui nisi reprehenderit proident et tempor quis cupidatat. Cillum deserunt eiusmod Lorem commodo consequat.",
    "date": "22.12.2019",
    "name": "Дмитрий",
  },
  {
    "id": 31,
    "item_id": 1030,
    "text": "Nisi amet laborum cupidatat culpa aliqua exercitation nisi nulla laborum deserunt ad proident est id. Ad commodo ea quis nisi magna aliquip eu consectetur irure ullamco sint eu qui fugiat. Tempor proident mollit excepteur aliqua commodo incididunt consequat excepteur incididunt anim.",
    "date": "11.01.2018",
    "name": "Андрей",
  },
  {
    "id": 32,
    "item_id": 1031,
    "text": "Occaecat tempor laboris amet consequat pariatur. Id sint sit non commodo. Anim id eu ad excepteur qui elit minim reprehenderit cupidatat exercitation aute dolor ea.",
    "date": "06.03.2020",
    "name": "Наталья",
  },
  {
    "id": 33,
    "item_id": 1032,
    "text": "Officia adipisicing tempor irure voluptate. Enim nisi nisi consequat aliquip dolor enim ut. Proident pariatur incididunt nisi qui duis veniam qui non eiusmod.",
    "date": "02.02.2014",
    "name": "Артём",
  },
  {
    "id": 34,
    "item_id": 1033,
    "text": "Adipisicing ad amet tempor adipisicing excepteur labore consequat mollit cupidatat dolor officia quis veniam. Sint nulla Lorem nostrud velit consequat est duis ad elit dolore. Fugiat esse Lorem mollit nostrud magna commodo sint velit cupidatat duis aute.",
    "date": "28.03.2014",
    "name": "Роза",
  },
  {
    "id": 35,
    "item_id": 1034,
    "text": "Ea velit commodo est laboris duis deserunt reprehenderit consectetur dolor laborum excepteur. Incididunt dolore adipisicing sit duis commodo enim do occaecat. Qui Lorem fugiat aute consequat labore cillum aute laborum tempor qui.",
    "date": "07.10.2018",
    "name": "Елизавета",
  },
  {
    "id": 36,
    "item_id": 1035,
    "text": "Labore aute esse eu ad occaecat duis duis qui est. Anim sunt nostrud eu reprehenderit cillum labore in occaecat. Ex ut quis cillum consectetur laborum ipsum eiusmod eu deserunt quis quis et adipisicing.",
    "date": "21.04.2017",
    "name": "Любовь",
  },
  {
    "id": 37,
    "item_id": 1036,
    "text": "Fugiat dolor occaecat ullamco elit. Cillum sit ea fugiat excepteur irure veniam adipisicing consectetur eu est. Sint incididunt excepteur irure do elit est esse magna.",
    "date": "28.01.2018",
    "name": "Елизавета",
  },
  {
    "id": 38,
    "item_id": 1037,
    "text": "Sunt nisi ea id elit duis incididunt. Elit id Lorem commodo est in officia consectetur pariatur voluptate voluptate. Nisi ad ipsum irure quis in.",
    "date": "07.12.2018",
    "name": "Александра",
  },
  {
    "id": 39,
    "item_id": 1038,
    "text": "Eiusmod in ex ipsum labore proident proident Lorem laboris non. Aliqua qui adipisicing sunt ipsum non aliqua dolore ea. Nostrud duis pariatur tempor adipisicing consequat pariatur.",
    "date": "26.03.2016",
    "name": "Николай",
  },
  {
    "id": 40,
    "item_id": 1039,
    "text": "Pariatur id id fugiat in laboris quis qui. Duis est tempor aute veniam esse labore aliquip deserunt officia do consequat reprehenderit. Ut nostrud exercitation Lorem dolor nostrud dolore dolor reprehenderit incididunt pariatur occaecat eu enim.",
    "date": "01.05.2017",
    "name": "Артём",
  },
  {
    "id": 41,
    "item_id": 1040,
    "text": "Culpa sunt laborum quis esse proident aliquip aliquip. Pariatur Lorem et ea officia ipsum eu. Aute ad anim cillum mollit occaecat officia minim et esse minim officia ullamco deserunt.",
    "date": "20.06.2014",
    "name": "Ксения",
  },
  {
    "id": 42,
    "item_id": 1041,
    "text": "Et qui velit labore culpa ut. Lorem Lorem eu consequat esse minim sit eiusmod nulla irure aliquip quis tempor. Officia quis consequat laboris labore nostrud ea excepteur elit consectetur cupidatat.",
    "date": "11.03.2018",
    "name": "Александра",
  },
  {
    "id": 43,
    "item_id": 1042,
    "text": "Minim occaecat culpa magna sunt eiusmod esse deserunt occaecat sunt mollit aute ad. Nisi cillum deserunt adipisicing cillum qui irure ipsum voluptate et. Laboris consequat Lorem reprehenderit eiusmod eiusmod labore.",
    "date": "23.07.2020",
    "name": "Дмитрий",
  },
  {
    "id": 44,
    "item_id": 1043,
    "text": "Enim id veniam veniam amet labore non enim incididunt. Laborum laboris excepteur exercitation occaecat ad consequat eiusmod deserunt amet id cupidatat minim. Elit elit et non eiusmod ad cupidatat.",
    "date": "01.08.2020",
    "name": "Кирилл",
  },
  {
    "id": 45,
    "item_id": 1044,
    "text": "Aliqua voluptate mollit elit consectetur ullamco ex adipisicing enim amet. Do non magna ex duis excepteur exercitation mollit minim non proident do est Lorem. Pariatur sint ipsum qui ex dolore pariatur irure ex.",
    "date": "04.06.2016",
    "name": "Ксения",
  },
  {
    "id": 46,
    "item_id": 1045,
    "text": "Id occaecat et sit non exercitation dolore dolore. Nostrud incididunt deserunt Lorem incididunt velit. Fugiat duis consequat proident et velit eiusmod nulla sunt culpa aliqua amet ipsum officia.",
    "date": "20.08.2019",
    "name": "Анастасия",
  },
  {
    "id": 47,
    "item_id": 1046,
    "text": "Excepteur nisi laborum officia pariatur velit. Lorem pariatur ipsum occaecat qui consectetur ex laborum culpa aliquip amet dolor quis. Veniam ea officia excepteur enim ea dolore dolor.",
    "date": "04.01.2016",
    "name": "Кирилл",
  },
  {
    "id": 48,
    "item_id": 1047,
    "text": "Id officia sunt amet sint fugiat occaecat eu commodo dolore duis anim ex consequat laborum. Incididunt proident exercitation consequat consequat consequat. Ea sit non et ullamco labore magna commodo pariatur nulla dolore in pariatur ipsum.",
    "date": "16.09.2015",
    "name": "Наталья",
  },
  {
    "id": 49,
    "item_id": 1048,
    "text": "Commodo eu non elit aute veniam est in sit excepteur duis fugiat. Aliquip sunt ad eu consectetur exercitation irure cillum Lorem dolore ad aliqua mollit. Laboris anim amet qui velit occaecat aliquip sit commodo.",
    "date": "25.08.2014",
    "name": "Екатерина",
  },
  {
    "id": 50,
    "item_id": 1049,
    "text": "Ut commodo ex aute cillum eiusmod pariatur esse excepteur incididunt aute voluptate occaecat ullamco. Amet cupidatat pariatur elit commodo. Sit ut reprehenderit incididunt excepteur.",
    "date": "21.10.2017",
    "name": "Елизавета",
  },
  {
    "id": 51,
    "item_id": 1050,
    "text": "Fugiat velit Lorem deserunt velit ipsum do. Excepteur magna ex incididunt sit ut incididunt consectetur laboris duis sit anim ullamco. Dolor proident amet nulla do quis veniam velit tempor sunt exercitation.",
    "date": "02.03.2014",
    "name": "Анастасия",
  },
];